Feature: Reusable slider & refactor sliders
asoltd/guilds pull request #119
Opened 2022-11-09 21:48 UTC by JakubFrackowiak

Resolves: #115 
Fullscreen: 
![image](https://user-images.githubusercontent.com/91438451/200948582-3e6d484e-c7f0-4f1a-958a-eefa15fed38f.png)

Mobile: 
![image](https://user-images.githubusercontent.com/91438451/200948731-a1eea239-d094-4a9b-913b-3d5b652c3d93.png)

2022-11-14 14:35 UTC, piotrostr commented
the green button is off on mobile

2022-11-14 14:36 UTC, piotrostr commented
the text should not be black in the dark theme

2022-11-14 14:54 UTC, piotrostr requested changes

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/ReusableSlider.tsx
> +  variant: "hero" | "team" | "quest" | "role"
use Enums here

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/ReusableSlider.tsx
> +      case "hero":
match against enums

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/ReusableSlider.tsx
> +interface Item extends Hero, Team, Quest, RoleType {}
if the Item extends all of those types it becomes an extremely general type, basically `any`

I would suggest to use `item = item as SomeType`

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/SliderButtons.tsx
> +  variant: "hero" | "quest" | "team" | "role"
DRY

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/SliderHeader.tsx
> +        <Typography variant="body1" color="text.secondary">
those could be mapped out

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/SliderHeader.tsx
> +      case "quest":
this is also repeated

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/ReusableSlider.tsx
> +import { Team } from "storage/team"
no absolute imports

2022-11-14 14:54 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/SliderButtons.tsx
> +        return <HeroesSliderButtons />
no need to wrap this into a function and proc it, drop the `renderButtons`

2022-11-17 14:12 UTC, piotrostr requested changes

2022-11-17 14:12 UTC, piotrostr commented on components/ReusableComponents/ReusableSlider/SliderButtons.tsx
> +            width: "11rem",
11rem is a bit much, use a max-width and some of sm, lg, xl etc

2022-11-19 16:26 UTC, JakubFrackowiak commented on components/ReusableComponents/ReusableSlider/SliderButtons.tsx
> +            width: "11rem",
I deleted the width prop entirely from all button variants. I used the whiteSpace="nowrap" to make text always stay in one line on the button.  Using for eg. maxWidth="md" doesnt really work on mui buttons.

2022-11-25 12:19 UTC, piotrostr requested changes
The directory should not be named ReusableComponents, I would suggest to keep the Slider in the main components directory and there is no need to indicate it's reusability so explicitly.

2022-12-02 01:13 UTC, piotrostr requested changes

2022-12-02 01:13 UTC, piotrostr commented on components/LatestQuestsSlider/index.tsx
> +          <Stack direction="row" justifyContent="space-between">
how does this scale on mobile?

2022-12-02 17:55 UTC, JakubFrackowiak commented on components/LatestQuestsSlider/index.tsx
> +          <Stack direction="row" justifyContent="space-between">
So accually there is no LatestQuestSlider component due to reusable one existing, I ll attach a screen of a slider on mobile

2022-12-05 16:46 UTC, JakubFrackowiak commented on components/LatestQuestsSlider/index.tsx
> +          <Stack direction="row" justifyContent="space-between">
![image](https://user-images.githubusercontent.com/91438451/205693893-20f8947b-6e00-48bd-9840-378dc6bb981e.png)

![image](https://user-images.githubusercontent.com/91438451/205693955-1ad819b7-3a1c-4723-9538-9d737735ab40.png)

@piotrostr

2022-12-17 18:34 UTC, JakubFrackowiak commented
all the other sliders should be deleted, only reusable one should be left

2022-12-21 11:53 UTC, JakubFrackowiak commented
Conflicts are resolved now @piotrostr

2023-01-05 15:32 UTC, piotrostr approved these changes

2023-01-24 14:30 UTC, merged