Feature: mentor card
asoltd/guilds pull request #120
Opened 2022-11-11 09:29 UTC by rpollock03

Resolves #103 (and part of 113) 

Add **reusable mentor card component**. Also add the **parent component to search for mentors**, including retrieval of mentors from Firebase. **Components displayed static side-by-side for now, but will be displayed in carousel as part of future pull request** (@JakubFrackowiak has built a universal carousel/slider component that has not yet been merged).

![Screenshot 2022-11-11 at 09 00 36](https://user-images.githubusercontent.com/49661708/201308740-99d575d3-fb9b-448b-a946-43b8caedc0cf.png)

**Important**: There was a decision about whether to have separate 'mentors' collection, or to include 'mentor' data as part of hero data. After discussing with Oli I have gone with the second option which is more efficient, because we don't have to make two separate requests for each mentor (considering shared name, level, bio, profile picture etc). 

So I have updated the 'hero' type to include mentor data like below. There will likely be more properties to add to this, but this is what is needed for now. The 'isMentor' boolean allows us to filter for active mentors, without user having to delete the mentor object each time which is the best way to do this I think.

![Screenshot 2022-11-11 at 09 11 46](https://user-images.githubusercontent.com/49661708/201308792-134bbabf-b2af-4f37-93c6-9ab3f88dce64.png)

On Firebase:

![Screenshot 2022-11-10 at 20 03 43](https://user-images.githubusercontent.com/49661708/201309108-81d4b9f7-9259-4858-8854-651dd4f56921.png)

2022-11-14 14:32 UTC, piotrostr requested changes

2022-11-14 14:32 UTC, piotrostr commented on components/SearchMentors/MentorCard.tsx
> +        <MentorPicture storagePath={`${mentor?.profilePicture}`} />
null chaining is redundant, this is checked in the parent component

2022-11-14 14:32 UTC, piotrostr commented on components/SearchMentors/MentorCard.tsx
> +          >{`Between £${mentor?.mentor.minRate} - £${mentor?.mentor.maxRate} p/h`}</Typography>
style error, not formatted correctly

2022-11-14 14:32 UTC, piotrostr commented on components/SearchMentors/MentorCard.tsx
> +export function MentorCard({ mentor }: MentorProps) {
add some slight padding, maybe justify the text a bit? the screenshot looks a bit wonky

2022-11-14 14:32 UTC, piotrostr commented on components/SearchMentors/index.tsx
> +
why empty line?

2022-11-15 19:08 UTC, rpollock03 commented on components/SearchMentors/MentorCard.tsx
> +export function MentorCard({ mentor }: MentorProps) {
Done. Apologies, was planning to finalise styling when adding to the universal slider.

2022-11-15 19:19 UTC, rpollock03 commented
Hi @piotrostr I fixed styling issue and other nits. Should be good to merge. I will update this to use mentor cards with the new universal slider component when it is built/merged. Thanks. 
![Screenshot 2022-11-15 at 19 14 37](https://user-images.githubusercontent.com/49661708/202006569-44116eed-2fd2-491c-ae2c-3e3752e57613.png)

2022-11-17 01:04 UTC, piotrostr approved these changes

2022-11-17 01:05 UTC, piotrostr commented
looking good, pls merge @rpollock03

2022-11-17 09:15 UTC, merged