Feature: reusable month top users (eg. month top questers)
asoltd/guilds pull request #143
Opened 2022-12-01 20:03 UTC by JakubFrackowiak

2022-12-02 01:05 UTC, piotrostr requested changes
please also add some padding, it looks a bit packed

2022-12-02 01:05 UTC, piotrostr commented on components/MonthTopUsers/User.tsx
> +            1,252 XP gained
make XP gained props

2022-12-02 01:06 UTC, piotrostr commented
and also please include the reusable buttons, should be merged soon

2022-12-02 17:52 UTC, JakubFrackowiak commented on components/MonthTopUsers/User.tsx
> +            1,252 XP gained
xpGained props is there, I suppose that it will be fetched from another database.

2022-12-17 18:34 UTC, piotrostr approved these changes
lgtm

2022-12-17 18:34 UTC, merged