Feature: tax info page
asoltd/guilds pull request #164
Opened 2022-12-22 22:27 UTC by rpollock03

Add tax info pages and new country select dropdown component
![Screenshot 2022-12-22 at 10 46 32](https://user-images.githubusercontent.com/49661708/209235658-38cc20db-f1ed-4d82-a0d1-655865cb0155.png)

- checks firebase for existing user tax info and pre-populates form with relevant data
- updates firebase with new data if all fields are populated.

![Screenshot 2022-12-22 at 10 52 34](https://user-images.githubusercontent.com/49661708/209235979-d7262375-46e1-4c98-8fed-a198cdf5eaaa.png)

![Screenshot 2022-12-22 at 10 41 15](https://user-images.githubusercontent.com/49661708/209236051-3cee9298-80aa-4160-b55d-57791c6afb68.png)

2022-12-24 17:58 UTC, rpollock03 commented
resolves #160

2022-12-24 18:44 UTC, piotrostr requested changes
looking good overall, some slight changes to be introduced

2022-12-24 18:44 UTC, piotrostr commented on components/CountrySelectDropdown.tsx
> +      /* defaultValue={{
no stranded comments

2022-12-24 18:44 UTC, piotrostr commented on components/CountrySelectDropdown.tsx
> +            alt=""
always include image `alt`

2022-12-24 18:44 UTC, piotrostr commented on components/CountrySelectDropdown.tsx
> +          <img
don't use the vanilla image, use `Image` from nextjs

2022-12-24 18:44 UTC, piotrostr commented on components/CountrySelectDropdown.tsx
> +export function CountrySelect(props) {
no props type specified, please add an interface and use de-structuring as well

2022-12-24 18:44 UTC, piotrostr commented on pages/taxinfo.tsx
> +  useEffect(() => {
this might not be safe, make sure the properties are there, if `hero.location` is undefined this will throw an error

2022-12-25 10:02 UTC, rpollock03 commented
> looking good overall, some slight changes to be introduced

Thanks, requested changes done.

2022-12-26 14:46 UTC, piotrostr commented on pages/taxinfo.tsx
> +    if (heroStatus == "success" && typeof hero.location != "undefined") {
would rather use null chaining or just ensuring that if the data is not there the UI is not going to break

please ensure that prior to merging, I'll LGTM still

2022-12-26 14:47 UTC, piotrostr approved these changes

2022-12-27 15:01 UTC, piotrostr approved these changes

2022-12-28 18:36 UTC, rpollock03 commented
Merged via a new PR due to conflicts in the bun lock files.

2022-12-28 18:36 UTC, closed without merging