Feature: Contract confirmation components
asoltd/guilds pull request #167
Opened 2022-12-29 16:59 UTC by rpollock03

Resolves #165 - builds component for contract confirmation page. This has been hard-coded for now, as the data in this page/component will be passed in from the bid terms components which have not been built yet. We can connect these up in future PR. 

![Screenshot 2022-12-29 at 16 50 34](https://user-images.githubusercontent.com/49661708/209984729-3b06fde9-2cd3-488a-ba82-1201fe99652e.png)
![Screenshot 2022-12-29 at 16 50 09](https://user-images.githubusercontent.com/49661708/209984700-6e341780-fa07-4b29-bc0a-635bf1bf6a6f.png)

Mobile: 
![Screenshot 2022-12-29 at 16 29 07](https://user-images.githubusercontent.com/49661708/209984710-98e99f4e-0337-4631-bf6c-7a0e673ee3ab.png)

2022-12-30 22:10 UTC, piotrostr commented
@rpollock03 I have mentioned this multiple times now, please don't create fork-based PR's, clone the repository and make new branches from the origin/master!

2022-12-30 23:09 UTC, rpollock03 commented
> @rpollock03 I have mentioned this multiple times now, please don't create fork-based PR's, clone the repository and make new branches from the origin/master!

No probs, can do that going forward 👍

2023-01-02 12:43 UTC, piotrostr requested changes

2023-01-02 12:43 UTC, piotrostr commented on components/Contracts/ContractConfirm.tsx
> +  fontSize: "14px",
no px for fonts

2023-01-02 12:43 UTC, piotrostr commented on components/Contracts/ContractConfirm.tsx
> +    alert("Contract accepted")
no `alert`, please use `Snackbar` from `@mui/material`, for working example please check out [here](https://github.com/asoltd/guilds/pull/93/commits/fc11115337d08e072acbeefeddbc32f898228116).

2023-01-03 12:55 UTC, rpollock03 commented on components/Contracts/ContractConfirm.tsx
> +  fontSize: "14px",
Fixed

2023-01-03 12:55 UTC, rpollock03 commented on components/Contracts/ContractConfirm.tsx
> +    alert("Contract accepted")
fixed (I only included alert as a temporary placeholder because we will need to add functions here once other components are built)

2023-01-03 12:55 UTC, rpollock03 commented
Not sure why the style check is failing here. It is passing locally... 
Checking formatting...
All matched files use Prettier code style!

2023-01-04 12:32 UTC, piotrostr approved these changes
lgtm! :)

2023-01-04 17:26 UTC, rpollock03 commented
Closing this pull request as there seems to be a bug in GitHub actions (the style check keeps failing even though it passes locally). Going to submit as a new PR without forking from external repository.

2023-01-04 17:26 UTC, closed without merging