refactor user card into reusable component
asoltd/guilds pull request #172
Opened 2023-01-09 18:42 UTC by rpollock03

-Bug fixes
-Profile cards are used in multiple places so refactored into reusable components:

SmallProfileCard:
![Screenshot 2023-01-09 at 18 40 47](https://user-images.githubusercontent.com/49661708/211383431-e6bb18e4-955f-4619-bf1b-79086132f7f7.png)
Medium Profile Card:
![Screenshot 2023-01-09 at 18 40 25](https://user-images.githubusercontent.com/49661708/211383446-f46ee025-3d6a-4f7c-a7b4-fd5ead2fc053.png)

2023-01-10 10:14 UTC, piotrostr requested changes

2023-01-10 10:14 UTC, piotrostr commented on components/ReusableComponents/UserCards.tsx
> +export function SmallUserCard({ photo, name, title }: SmallUserCardProps) {
There should be no `ReusableComponents` directory, please move the User Cards to regular components, those can be reused

Otherwise, this leads to situation in which you have to look for components in two separate directories

2023-01-10 17:56 UTC, rpollock03 commented on components/ReusableComponents/UserCards.tsx
> +export function SmallUserCard({ photo, name, title }: SmallUserCardProps) {
done. I have also moved the other components in that directory and deleted it.

2023-01-10 17:59 UTC, rpollock03 commented
Should be good now @piotrostr

2023-01-11 10:02 UTC, piotrostr approved these changes

2023-01-11 12:06 UTC, merged