Feature: add team/quest page banner
asoltd/guilds pull request #179
Opened 2023-01-17 21:59 UTC by rpollock03

Adding the banner that is used on the individual quest and team pages:

![Screenshot 2023-01-17 at 19 52 15](https://user-images.githubusercontent.com/49661708/213021069-7036a2a7-4b94-42f1-a284-6f2ee5581fd6.png)

A couple of fields are necessarily hard-coded at this stage, but I can fix that in due course.

2023-01-19 10:11 UTC, piotrostr requested changes

2023-01-19 10:11 UTC, piotrostr commented on components/IndividualQuestBanner.tsx
> +        storagePath={`quests/${"1200px-Calico_tabby_cat_-_Savannah.jpeg"}`}
make this component props and add to seed, consult yoni

2023-01-19 18:11 UTC, rpollock03 commented
requested changes made. Should be good to merge @piotrostr

2023-01-22 16:59 UTC, rpollock03 commented
this good to merge too @piotrostr ?

2023-01-22 17:23 UTC, piotrostr approved these changes

2023-01-22 17:23 UTC, piotrostr commented on components/IndividualQuestBanner.tsx
> +      <QuestImage storagePath={`quests/${quest?.image}`} alt="" />
please include the alt image property

2023-01-22 17:23 UTC, piotrostr commented
please just include the alt image as per above and it'll be good to merge

2023-01-22 17:35 UTC, rpollock03 commented on components/IndividualQuestBanner.tsx
> +      <QuestImage storagePath={`quests/${quest?.image}`} alt="" />
Thanks done. Resolving and merging.

2023-01-22 17:35 UTC, merged