Feature: populate bids with sample bids and display them
asoltd/guilds pull request #20
Opened 2022-09-07 14:07 UTC by OliwierOST

Resolves: #16. Added a function for populating bids and a component to display them. Also the pr includes the most efficient way to fetch subcollections from firestore using reactfire.

2022-09-09 11:45 UTC, piotrostr requested changes
Looking good, some minor touches. Please also have a look at the rundown on [how to structure data in firestore](https://firebase.google.com/docs/firestore/manage-data/structure-data), that is provided you haven't stumbled upon it already :)

2022-09-09 11:45 UTC, piotrostr commented on components/Quests.tsx
> +                <div style={{ margin: "auto" }}>no bids</div>
nit: fix brain typo

this should be no *quests* not bids right?

2022-09-09 11:45 UTC, piotrostr commented on storage/quest/populate.ts
> +    promises.push(setDoc(questRef, quest))
optional: instead of using the `faker.datatype.uuid()` you may use the firestore's `addDoc`

Using the `addDoc` creates a UUID automatically, using the `setDoc` you need to specify the id yourself. Leaving this up to you.

2022-09-09 16:52 UTC, OliwierOST commented on storage/quest/populate.ts
> +    promises.push(setDoc(questRef, quest))
updated populate functions to create documents with auto generated ids and stored these ids inside of the documents as field values

2022-09-11 22:51 UTC, piotrostr requested changes

2022-09-11 22:51 UTC, piotrostr commented on storage/quest/populate.ts
> +    const questId = questRef.id
`questId` variable is redudant, no need to set it

2022-09-11 22:51 UTC, piotrostr commented on storage/quest/populate.ts
> +      const bidId = bidRef.id
Same as `questId` this variable is also redundant

2022-09-11 22:51 UTC, piotrostr commented on storage/quest/populate.ts
>    const results = await Promise.all(promises)
check the result if the adding was successful and notify the user

2022-09-18 18:53 UTC, piotrostr commented
@OliwierOST

2022-09-20 23:43 UTC, piotrostr requested changes

2022-09-20 23:43 UTC, piotrostr commented on storage/quest/types.ts
>    description: string
Quest needs to have ID as well

2022-09-20 23:43 UTC, piotrostr commented on components/Quests.tsx
> +                    <Bids path={`quests/${quest.NO_ID_FIELD}/bids`} />
no all-caps constants as part of objects, only environment variables and secrets

2022-09-21 14:17 UTC, OliwierOST commented on storage/quest/types.ts
>    description: string
The ID itself is stored as document "name". Thought it was redundant, might as well store it within the document as a field, just for convinience.

2022-09-21 18:10 UTC, OliwierOST commented
Usage of setDoc instead of addDoc might be confusing if we're auto generating the ID for the document. The reason is that setDoc takes the document as an argument while addDoc takes the collection. The ID is generated the moment we obtain the document reference and if no specified ID is passed to setDoc it creates the document with the auto generated id anyway. Say we wanted to have the same ID as a document "name" also inside of a document as a field, we would need to use the same document reference for both of those actions. It wouldn't be possible if we were to pass a collection as an argument to the addDoc function. Hope it resolves the confusion :)

2022-09-21 23:46 UTC, piotrostr commented on storage/quest/types.ts
>    description: string
It is not redundant to store the ID as part of the document, it provides a lot of convenience to tiny storage requirement

The key might not always be there when pulling batch data, it is useful to contain it in the document as well

2022-09-21 23:52 UTC, piotrostr requested changes
needs just a small IDs touch and some additional explanation

2022-09-21 23:52 UTC, piotrostr commented on components/Quests.tsx
> +                    <Bids path={`quests/${quest.id}/bids`} />
good example of that is here, the key won’t always be there but having the ID in the body is handy when creating relationships or Google Storage paths

2022-09-21 23:52 UTC, piotrostr commented on storage/quest/types.ts
> +  id: UUID
again, the corresponding `questID` can also be included here

2022-09-23 18:54 UTC, piotrostr requested changes

2022-09-23 18:54 UTC, piotrostr commented on components/Quests.tsx
> +        style={{ color: "black" }}
Don't mix inline styles when using styled-components, possibly move to global css

2022-09-23 18:54 UTC, piotrostr commented on components/Quests.tsx
> +                    <div>Reward: {quest?.reward}</div>
The fields should have custom components, like `QuestProperty`

2022-09-23 18:54 UTC, piotrostr commented on components/Quests.tsx
> +                    <div>Tags: {quest?.tags[0]}</div>
Never do this kind of indexing, makes the component less versatile

Rather, map out the tags in the `div`

Again, use a custom component for the `Tag`'s so that styling is a breeze

2022-09-23 18:54 UTC, piotrostr commented on storage/quest/types.ts
> +  questId: UUID
`questId` -> `id`

2022-09-23 18:54 UTC, piotrostr commented on storage/quest/types.ts
>    createdAt: Date
Either both `createdAt` and `updatedAt` as optional or neither

2022-09-23 21:23 UTC, closed without merging