Messaging functionality
asoltd/guilds pull request #21
Opened 2022-09-08 11:53 UTC by rpollock03

Fix #19 - implements skeleton messaging component using Stream SDK. Note: I signed up for 30day trial, to use beyond this we will need to purchase an account. 

As discussed by Slack will implement Firebase authentication for this separately. 

![Screenshot 2022-09-08 at 12 50 41](https://user-images.githubusercontent.com/49661708/189115172-23b11608-d8df-4a12-8a00-f8f845a1cc0c.png)

2022-09-09 11:02 UTC, piotrostr commented on components/Messaging.tsx
> +        //chat description
nit: comments should start with a whitespace

```ts
// GOOD
// chat description

// BAD
//chat description
```

2022-09-09 11:15 UTC, piotrostr requested changes

2022-09-09 11:15 UTC, piotrostr commented on package.json
> +    "next": "^12.2.5",
deps: please try not to update major dependencies in per-feature pull requests, adding `stream-chat` dependency is perfectly fine, yet changing the next version might lead to conflicts.

2022-09-09 11:15 UTC, piotrostr commented on components/Messaging.tsx
> +// Replace with Firebase Auth
nit: include a TODO(rob) in the comment to keep it neat

2022-09-09 11:15 UTC, piotrostr commented on components/Messaging.tsx
> +  useEffect(() => {
fix: move any of the data outside of the `useEffect` 

* use `useState` hooks with initial value of the hardcoded user
* create a `User` and `Channel` interfaces and annotate the `useState`s accordingly
* move the user and channel to `useState<User>(user)`, `useState<Channel>(channel)`
* include the `user, channel` in the `useEffect` dependency array

Even though the `useState` hooks might not be used for the sake of the `reactfire` hooks that will likely be used in the next pull request, I suggest we adhere to the best practices even for WIP features.

2022-09-13 21:44 UTC, rpollock03 commented on package.json
> +    "next": "^12.2.5",
Thanks, I have installed version 12.2.3

2022-09-13 22:41 UTC, rpollock03 commented on components/Messaging.tsx
> +  useEffect(() => {
done

2022-09-13 22:43 UTC, rpollock03 commented
@piotrostr for review. Streamchat auth integrated, and I have addressed your comments/suggestions. Thanks.

2022-09-18 19:09 UTC, piotrostr requested changes

2022-09-18 19:09 UTC, piotrostr commented on package.json
> -    "next": "12.2.3",
Again, please don't update dependencies that are not directly related to the feature in separate pull request, Rob

In case you do feel like we should bump a dependency, please create a Dependabot-like PR

Alternatively we could also leave all of the dependency updates to the Dependabot, in fact it has an already awaiting PR to bump the NextJS to the newer version! :)

2022-09-21 13:13 UTC, rpollock03 commented on components/Messaging.tsx
> +    name: user?.displayName,
True, I have updated to remove this

2022-09-21 13:14 UTC, rpollock03 commented on package.json
> -    "next": "12.2.3",
Current version in master is 12.2.3. I updated to 12.2.4 in previous PR, but then have reverted to 12.2.3 here as per your previous comment. Hopefully this is ok

2022-09-21 23:43 UTC, piotrostr requested changes

2022-09-21 23:43 UTC, piotrostr commented on pages/index.tsx
> +      <div style={{ display: "block", marginTop: 2500 }}>
Never use units in this way, 2500px margin scales horribly among devices and is not versatile

2022-09-21 23:43 UTC, piotrostr commented on package.json
> -    "next": "12.2.3",
There is still a change to the next dep that should not be there, please revert

2022-09-22 21:39 UTC, rpollock03 commented on pages/index.tsx
> +      <div style={{ display: "block", marginTop: 2500 }}>
Yes this was only a temporary solution to put spacing between the test components because we had these all on the same page. Since we are building skeleton pages I can remove this anyway.

2022-09-22 22:29 UTC, closed without merging