feature: add reusable switch and formlabel components
asoltd/guilds pull request #223
Opened 2023-07-07 17:51 UTC by rpollock03

![Screenshot 2023-07-04 at 12 54 14](https://github.com/asoltd/guilds/assets/49661708/4bc6d40d-4254-417c-b0d6-8a17a757c28f)
![Screenshot 2023-07-05 at 16 49 26](https://github.com/asoltd/guilds/assets/49661708/742ad609-9ffe-4093-8b43-ce1a156d30fa)

2023-07-07 21:48 UTC, OliwierOST requested changes
Some minor changes and all good

2023-07-07 21:48 UTC, OliwierOST commented on components/FormInputLabel.tsx
> +        sx={{ fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: 500 }}
Instead of using fontSize use `variant` prop.`lineHeight` and `fontWeight` could also be props instead of putting it in `sx`

2023-07-07 21:48 UTC, OliwierOST commented on components/FormInputLabel.tsx
> +        sx={{ fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: 500 }}
Same for here

2023-07-08 08:15 UTC, rpollock03 commented on components/FormInputLabel.tsx
> +        sx={{ fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: 500 }}
done. There was no existing variant so I had to make a new one for forms.

2023-07-08 08:15 UTC, rpollock03 commented on components/FormInputLabel.tsx
> +        sx={{ fontSize: "0.875rem", lineHeight: "1.25rem", fontWeight: 500 }}
done

2023-07-08 11:57 UTC, OliwierOST approved these changes
LGTM!

2023-07-08 11:57 UTC, merged