feature: add settings page and toggle nav
asoltd/guilds pull request #224
Opened 2023-07-08 09:26 UTC by rpollock03

![Screenshot 2023-07-08 at 10 24 02](https://github.com/asoltd/guilds/assets/49661708/3899bb38-e3f8-458e-b873-67c50c098f56)

2023-07-08 12:04 UTC, OliwierOST commented
I think we could make the toggle nav reusable as it appears in multiple places throughout the website, e.g Quests Hub (Client) on Figma. Let's pass the navigation items as props to the component.

2023-07-16 19:59 UTC, rpollock03 commented
> I think we could make the toggle nav reusable as it appears in multiple places throughout the website, e.g Quests Hub (Client) on Figma. Let's pass the navigation items as props to the component.

Thanks @OliwierOST, I have made this into a reusable component.

2023-07-22 12:08 UTC, rpollock03 commented on components/FormField/index.tsx
> +  type = "",
This is necessary to allow form fields to be password fields for example.

2023-07-24 16:09 UTC, oliwierost requested changes
Some minor changes. Other than that very good work! Keep it up!

2023-07-24 16:35 UTC, rpollock03 commented on components/FormDropdown/index.tsx
> +          return (
done

2023-07-24 16:35 UTC, rpollock03 commented on components/FormDropdown/index.tsx
> +  icon?: any
This doesn't work, trying to find alternatives

2023-07-24 16:42 UTC, rpollock03 commented on components/Settings/accountTab.tsx
> +      })
done

2023-07-24 16:53 UTC, rpollock03 commented on components/Settings/securityTab.tsx
> +          onSubmit={async (values) => {
done

2023-07-24 16:56 UTC, rpollock03 commented on components/PrimaryButton/index.tsx
> +  form,
done

2023-07-24 17:02 UTC, rpollock03 commented on components/FormField/index.tsx
> +  changeState,
done

2023-07-24 17:34 UTC, rpollock03 commented on components/Settings/balancesTab.tsx
> +      <Stack direction={"row"} justifyContent="flex-end" mt={1} spacing={1}>
fixed

2023-07-24 17:53 UTC, rpollock03 commented on components/FormDropdown/index.tsx
> +  icon?: any
fixed

2023-07-24 17:59 UTC, rpollock03 commented on components/Settings/accountTab.tsx
> +        /* TODO - add arrayUnion to save tags */
done

2023-07-24 18:08 UTC, rpollock03 commented
all requested changes made @oliwierost , should be good to merge!

2023-07-24 19:23 UTC, oliwierost approved these changes
Very good! Keep an eye on little stylistic issues, e.g. when passing prop dont't do `label={"Name"}`, instead do ` label="Name"`. Also a lot of components let you use padding and marigin directly as a prop like this: `px={4}`. We'd rather wan't to use that approach instead of `sx={{ px: 4 }}`. Other than that a lot of improvements and overall very nice!

2023-07-24 19:23 UTC, merged