Feature: Placeholder for the stats page tabs
asoltd/guilds pull request #37
Opened 2022-09-22 15:43 UTC by JakubFrackowiak

Add working buttons that open different stats components.

2022-09-23 19:27 UTC, piotrostr requested changes

2022-09-23 19:27 UTC, piotrostr commented on components/ExperienceAndRewiews.tsx
> +export default function ExperienceAndRewiews(): JSX.Element {
*Reviews

2022-09-23 19:27 UTC, piotrostr commented on components/FreelancerBids.tsx
> +  const bidsRef = collection(firestore, "quests/path.path/bids")
Did you mean `${path.path}`?

2022-09-23 19:27 UTC, piotrostr commented on components/Stats.tsx
> +  const tabs = ["Quests", "Profile", "Epirience And Reviews"]
*Experience

2022-09-23 19:27 UTC, piotrostr commented on components/Stats.tsx
> +  function Tab(tabName): JSX.Element {
Specify type of `tabName`

2022-09-23 19:27 UTC, piotrostr commented on components/Stats.tsx
> +            setShowStats(tabName.tabName)
Unclear name, don't add object keys of the same name as the object variable

How about making it `tab.name`?

2022-09-23 19:27 UTC, piotrostr commented on pages/stats.tsx
> +import Stats from "components/Stats"
Don't do default imports/exports for components

2022-09-23 19:27 UTC, piotrostr commented on storage/quest/populate.ts
Unstage the `populate.ts` file as it has changed, alternatively merge the current `main` branch into `stats-page-tabs` branch

2022-09-23 19:27 UTC, piotrostr commented on storage/quest/types.ts
>    id?: string
Same, this file has also changed

2022-09-25 22:30 UTC, OliwierOST requested changes

2022-09-25 22:30 UTC, OliwierOST commented on components/AllStats.tsx
> +      {quests?.map((quest, idx) => (
Quest should have a type

2022-09-25 22:30 UTC, OliwierOST commented on components/AllStats.tsx
> +      {biddingQuests?.map((biddingQuest, idx) => (
BiddingQuest as well should have a type

2022-09-25 22:30 UTC, OliwierOST commented on components/Stats.tsx
> +  const tabs = ["Quests", "Profile", "Experience And Reviews"]
Please instead of mapping through tabs array make separate component for each tab.

2022-09-25 22:30 UTC, OliwierOST commented on components/Stats.tsx
> +      <div>
This div could be an empty tag

2022-09-25 22:30 UTC, OliwierOST commented on components/Stats.tsx
> +  const tabs = ["Quests", "Profile", "Experience And Reviews"]
You could make a folder for all components for tabs

2022-09-25 22:34 UTC, piotrostr commented on components/Stats.tsx
> +  const tabs = ["Quests", "Profile", "Experience And Reviews"]
**Should**, we don't want a flood in the components folder lol

2022-09-25 22:35 UTC, piotrostr requested changes

2022-09-25 22:35 UTC, piotrostr commented on components/AllStats.tsx
> +          <div>{bid?.amount}</div>
This should be mapping into `<Bid />` components

2022-09-27 19:02 UTC, OliwierOST requested changes

2022-09-27 19:02 UTC, OliwierOST commented on components/Tabs/QuestStats.tsx
> +export function FreelancerBids(path): JSX.Element {
Also what type does it have?

2022-09-27 21:36 UTC, OliwierOST requested changes

2022-09-27 21:36 UTC, OliwierOST commented on components/Tabs/QuestStats.tsx
> +                  biddingQuests?.map((biddingQuest: Bid, idx) => (
Notice how confusing the name biddingQuest is. You can see that it's actually a Bid by it's type. I would suggest changing it to something like userBids or currentUserBids.

2022-10-01 22:21 UTC, OliwierOST commented
There are still some unresolved changes @JakubFrackowiak, please have another look

If it is a false-positive, please mark the outstanding unresolved comments and get me a green light! :)

As of now, merging is still blocked

2022-10-01 22:34 UTC, OliwierOST requested changes

2022-10-01 22:34 UTC, OliwierOST commented on components/Stats.tsx
> +import { QuestsStats } from "components/Tabs/QuestStats"
There should be no absolute imports

Please make changes everywhere this occurs

2022-10-01 22:34 UTC, OliwierOST commented on components/Stats.tsx
> +  function Tabs(tab): JSX.Element {
The tab should have a type specified in `interface Props {...}`

2022-10-01 22:34 UTC, OliwierOST commented on components/Stats.tsx
> +        <Button>
We are using the MUI components library for the project

Please use them here wherever you can for consistency

2022-10-01 22:34 UTC, OliwierOST commented on components/Tabs/ExpirienceAndReviews.tsx.tsx
> +export function ExperienceAndReviews(): JSX.Element {
What is the intended purpose for this component?

2022-10-01 22:34 UTC, OliwierOST commented on components/Tabs/QuestStats.tsx
> +export function FreelancerBids({ path }): JSX.Element {
The prop `path` should be given a type

2022-10-07 13:46 UTC, JakubFrackowiak commented on components/Tabs/ExpirienceAndReviews.tsx.tsx
> +export function ExperienceAndReviews(): JSX.Element {
Tab for expirience and reviews?

2022-10-07 13:53 UTC, JakubFrackowiak commented on components/Tabs/QuestStats.tsx
> +export function FreelancerBids({ path }): JSX.Element {
component not working with type for path

2022-10-12 12:47 UTC, OliwierOST commented
Please refactor the components and use the MUI library. We can't hold PRs for so long

2022-10-29 16:08 UTC, closed without merging