Feature: add/edit Hero profile data
asoltd/guilds pull request #53
Opened 2022-09-27 16:47 UTC by rpollock03

Skeleton component and functionality for a hero to add or update their profile data.

Logged in users view a basic component that looks like this:

![Screenshot 2022-09-27 at 17 29 21](https://user-images.githubusercontent.com/49661708/192585344-b68b3bb2-d73c-459e-8924-5763a013d795.png)

Clicking the edit button displays a form allowing user to add, or update their profile information:

![Screenshot 2022-09-27 at 17 29 48](https://user-images.githubusercontent.com/49661708/192585648-eb199b11-5ac3-469e-bc86-b844f2b77b6a.png)

Note: the fields of the form are pre-populated with any existing user profile data found on firebase (the document ID on firebase is the same as the userId). In this way, a new user can add their profile information, or an existing user can update profile information they have previously sent.

Includes an add experience button which allows the user to add as many experiences as needed to the experience array.

![Screenshot 2022-09-27 at 16 46 25](https://user-images.githubusercontent.com/49661708/192585973-4c722cf2-1307-43f0-963b-6d3a8090c714.png)

Firebase document consistent with <Hero> data type:

![Screenshot 2022-09-27 at 17 44 49](https://user-images.githubusercontent.com/49661708/192586618-fbb844cb-fc7a-4166-a223-02e51349bbd1.png)

2022-10-01 22:07 UTC, OliwierOST commented
<img width="228" alt="Screen Shot 2022-10-02 at 12 06 33 AM" src="https://user-images.githubusercontent.com/86793212/193430075-e6331770-4fc7-42e7-9151-a65c8b3643bf.png">

Above is redundant, information about logged in user can be found here

<img width="74" alt="Screen Shot 2022-10-02 at 12 06 55 AM" src="https://user-images.githubusercontent.com/86793212/193430087-268e1645-4282-4dd5-ac6b-489cef9cd1bb.png">

2022-10-01 22:18 UTC, OliwierOST requested changes

2022-10-01 22:18 UTC, OliwierOST commented on components/EditProfile.tsx
> +export default function EditProfile({ hero }): JSX.Element {
The type of props is not specified for `EditProfile`

Should declare an `interface Props {}`

2022-10-01 22:18 UTC, OliwierOST commented on components/EditProfile.tsx
> +export default function EditProfile({ hero }): JSX.Element {
As mentioned before, there should be no default exports except for pages

2022-10-01 22:18 UTC, OliwierOST commented on components/EditProfile.tsx
> +  const initialValues = {
Instead of `hero ? hero.property` do `hero?.property || ""`

2022-10-01 22:18 UTC, OliwierOST commented on components/EditProfile.tsx
> +  const handleSubmit = async (values) => {
The `values` should have a type defined

2022-10-01 22:18 UTC, OliwierOST commented on components/EditProfile.tsx
> +    <div>
We are using MUI component library for the project, please use it here as well

2022-10-01 22:18 UTC, OliwierOST commented on components/Profile.tsx
> +    if (status === "success" && user) getHeroData()
nit: one-line if statements are not as readable, please split to regular, multi-line

2022-10-01 22:18 UTC, OliwierOST commented on components/Profile.tsx
> +      <div onClick={() => setEditMode(!editMode)}>
As per comment before, this is a redundant component

The user menu is already there in the header

2022-10-01 22:18 UTC, OliwierOST commented on components/Profile.tsx
> +      {editMode ? <EditProfile hero={heroData} /> : null}
Should be `{editMode && <EditProfile hero={heroData} />}`

2022-10-01 22:18 UTC, OliwierOST commented on components/Profile.tsx
> +  const [heroData, setHeroData] = useState({})
Rename `heroData` to `hero` to stay consistent

The `Hero` component accepts `hero` props, not `heroData`

2022-10-03 20:16 UTC, rpollock03 commented on components/EditProfile.tsx
> +export default function EditProfile({ hero }): JSX.Element {
thanks fixed

2022-10-03 20:17 UTC, rpollock03 commented on components/EditProfile.tsx
> +  const initialValues = {
true, I have changed.

2022-10-03 20:17 UTC, rpollock03 commented on components/EditProfile.tsx
> +    <div>
Cheers added

2022-10-03 20:17 UTC, rpollock03 commented on components/Profile.tsx
> +    if (status === "success" && user) getHeroData()
fixed thanks

2022-10-03 20:17 UTC, rpollock03 commented on components/Profile.tsx
> +      <div onClick={() => setEditMode(!editMode)}>
removed, thanks.

2022-10-03 20:18 UTC, rpollock03 commented on components/Profile.tsx
> +  const [heroData, setHeroData] = useState({})
done

2022-10-04 21:25 UTC, rpollock03 commented on components/EditProfile.tsx
> +  const handleSubmit = async (values) => {
Don't think we can do that at this stage. Can discuss on slack.

2022-10-22 15:16 UTC, OliwierOST requested changes

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +            <FormField
As we're using the MUI components library, you should change the FormField and every component possible to the ones coming from MUI. The MUI actually works pretty well with the formik package.

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +        {({ values, handleChange, handleBlur, handleSubmit, handleReset }) => (
All of the arguments that the function takes should have a type. The type can be imported directly from formik as FormikProps<ValuesType>

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +                          <label htmlFor={`experience.${index}.position`}>
Instead of label we would rather use the MUI Typography component

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +                          <label htmlFor={`experience.${index}.position`}>
Instead of label we would rather use the MUI Typography component

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +              render={({ remove, push }) => (
Define the type of remove and push, u could either create new interface or maybe import an existing type

2022-10-22 15:16 UTC, OliwierOST commented on components/Profile.tsx
> +        {" "}
is the empty string essential here?

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +            <Caption>First Name</Caption>
U could wrap the whole column with the MUI Stack component as it works as a flexbox essentially. Try to use it wherever you have evenly spaced components.

2022-10-22 15:16 UTC, OliwierOST commented on components/EditProfile.tsx
> +                        <div>
Same here, every div wrapper could be a Stack component

2022-10-25 18:18 UTC, closed without merging