script to populate teams
asoltd/guilds pull request #54
Opened 2022-09-27 17:25 UTC by prayash51

2022-09-28 12:06 UTC, OliwierOST requested changes

2022-09-28 12:06 UTC, OliwierOST commented on storage/team/populate.ts
> +      tags: [],
add the id to the document, u can do that by calling
const teamsRef = collection(firestore, `teams`)
const teamRef = doc(teamsRef)
...
id: teamRef.id
...
setDoc(teamRef, team)

2022-09-28 12:06 UTC, OliwierOST commented on storage/team/types.ts
> +  _id?: UUID
make the id required

2022-10-01 22:05 UTC, OliwierOST requested changes

2022-10-01 22:05 UTC, OliwierOST commented on components/Teams.tsx
> +        <button onClick={() => populateTeams(firestore)}>
We have some mock data already, so we need to drop the pattern of populating data on click

2022-10-01 22:05 UTC, OliwierOST commented on pages/index.tsx
> +import { Teams } from "components/Teams"
No absolute imports

2022-10-01 22:05 UTC, OliwierOST commented on storage/team/types.ts
> +  id: UUID
nit: the `id` field should always be located at the top of the interface declaration, before any other fields

2022-10-01 22:05 UTC, OliwierOST commented on storage/team/types.ts
> +import { UUID } from "./../common"
Should be just `"../common"`

2022-10-01 22:05 UTC, OliwierOST commented on storage/team/populate.ts
> +  } catch (e: any) {
Generally, `any` should not be used without justification

Please specify the types of errors one may expect

2022-10-03 11:39 UTC, OliwierOST commented
One note for improving future workflow. Try to make commit messages more explanatory and don't be afraid to make multiple commits resolving the comments.

2022-10-03 15:47 UTC, prayash51 commented on components/Teams.tsx
> +const Image = styled.img`
img tag changed to NextJS Image

2022-10-03 16:46 UTC, prayash51 commented on storage/team/types.ts
> +  id: UUID
Resolved

2022-10-04 13:53 UTC, OliwierOST commented
Please have another look at CONTRIBUTING.md and try to spot what you can improve. And please stay consistent with other components and pages.

2022-11-02 15:39 UTC, piotrostr commented
closing since it is outdated

2022-11-02 15:39 UTC, closed without merging