Feature: hero header component
asoltd/guilds pull request #67
Opened 2022-10-28 08:30 UTC by rpollock03

Resolves #57 - adds new hero header component, using MUI components and responsive design. Sign in component to be added separately. 

![Screenshot 2022-10-28 at 09 25 31](https://user-images.githubusercontent.com/49661708/198541962-19bf4f1e-e2e8-4b81-81bd-d24f4421f783.png)
![Screenshot 2022-10-28 at 09 25 53](https://user-images.githubusercontent.com/49661708/198541974-5ec15ef1-7f3a-4d17-84aa-42f88bde7073.png)

2022-10-29 13:02 UTC, piotrostr requested changes

2022-10-29 13:02 UTC, piotrostr commented on components/HeroHeader1.tsx
> +font-family: 'Plus Jakarta Sans'
bad indent

2022-10-29 13:02 UTC, piotrostr commented on components/HeroHeader1.tsx
> +font-weight: 600;
same as above, should be 2 spaces

2022-10-29 13:07 UTC, piotrostr requested changes

2022-10-29 13:07 UTC, piotrostr commented on pages/index.tsx
> +        <HeroHeader />
don't add any components to the pages, only work on separate files otherwise we will run into merge conflicts

2022-10-29 13:07 UTC, piotrostr commented on components/HeroHeader1.tsx
> +      <AuthContainer>{/*sign in / auth components here*/}</AuthContainer>
this is nice! adding comments like that will help others work with the code :)

2022-10-29 13:14 UTC, piotrostr requested changes

2022-10-29 13:14 UTC, piotrostr commented on components/HeroHeader1.tsx
> +        <Heading variant="h3">
Heading not visible in dark mode

<img width="749" alt="image" src="https://user-images.githubusercontent.com/63755291/198833515-41a161ea-4e26-450e-825d-d322e3116cfa.png">

2022-10-30 11:07 UTC, piotrostr commented
hey @rpollock03, please be sure to click 'Resolve conversation' having resolved it!

2022-10-30 13:54 UTC, rpollock03 commented
> hey @rpollock03, please be sure to click 'Resolve conversation' having resolved it!

Thanks done. Might have to submit a new PR. I cannot seem to get rid of the bun.lockb conflict :S

2022-10-30 14:02 UTC, closed without merging