Feature: add hero header component
asoltd/guilds pull request #77
Opened 2022-10-30 14:02 UTC by rpollock03

Resolves #57 - adds new hero header component, using MUI components and responsive design. Sign in component to be added separately. 

![Screenshot 2022-10-28 at 09 25 31](https://user-images.githubusercontent.com/49661708/198541962-19bf4f1e-e2e8-4b81-81bd-d24f4421f783.png)
![Screenshot 2022-10-28 at 09 25 53](https://user-images.githubusercontent.com/49661708/198541974-5ec15ef1-7f3a-4d17-84aa-42f88bde7073.png)

2022-10-31 09:35 UTC, piotrostr requested changes

2022-10-31 09:35 UTC, piotrostr commented on components/HeroHeader1.tsx
> +`
nit: add newline for correct spacing

2022-10-31 09:35 UTC, piotrostr commented on components/HeroHeader1.tsx
> +`
same here

2022-10-31 09:35 UTC, piotrostr commented on components/HeroHeader1.tsx
> +const Heading = styled(Typography)`
Rather than creating a one-off styled Typography component, it would be more elegant to add global styling and use Typography variants.

See https://mui.com/material-ui/customization/typography/#variants

2022-10-31 09:36 UTC, piotrostr commented on components/HeroHeader1.tsx
> +const Heading = styled(Typography)`
Be sure not to break any of the existing Typography'ies though! :)

2022-10-31 09:39 UTC, piotrostr commented
And one last thing, please be sure not to close the pull requests, rather rebase or perform a merge commit.

See https://www.atlassian.com/git/tutorials/merging-vs-rebasing

2022-10-31 18:01 UTC, rpollock03 commented on components/HeroHeader1.tsx
> +const Heading = styled(Typography)`
Good idea, I have updated to create custom global styling using typography variants (added to the same object that you created to add the Jakarta font)

2022-10-31 18:03 UTC, rpollock03 commented
@piotrostr grateful for your review, I have addressed your comments. In particular, and as you suggested, I have replaced one-off styled components with global styling using Typography variants, which I have included in the same place you added the Jakarta font (heroHeading and heroSubheading).

2022-11-01 15:14 UTC, piotrostr requested changes

2022-11-01 15:14 UTC, piotrostr commented on components/HeroHeader1.tsx
> +  font-weight: 600;
Could we also move this to `theme.ts`? The naming can just be different levels of h, like h1, h2, ..., h6 to be reused throughout the app.

2022-11-01 16:57 UTC, rpollock03 commented on components/HeroHeader1.tsx
> +  font-weight: 600;
this is quite a specific use case (green font etc) so not sure it makes sense to use h6 etc here as we won't be using elsewhere much, but I have moved to themes.ts as you have suggested.

2022-11-01 16:57 UTC, rpollock03 commented
> Perfect, one more thing - please don't include numbers in file names nor the component names.
> 
> `HeroHeader1` -> `HeroHeader`

Done.

2022-11-01 17:12 UTC, piotrostr requested changes
Looking good! Now the absolute last thing to do would be to check if the typography like one on the homepage appears elsewhere in the page design and then, adjust it to be the right heading/paragraph/span.

There might be a part of the design with all of the possible colors and fonts as well as the logos and so on somewhere on Figma, it could be useful to check for the above there as well.

Lastly, having checked that, please modify the default Typography variants rather than create the custom variants. 

For example (no exactly but along those lines): 
`reviewAverage` -> `span` but say with `color: gray`
or
`heroHeading` -> `h2`

Let me know if that makes sense.

2022-11-03 23:26 UTC, piotrostr approved these changes

2022-11-03 23:27 UTC, merged