Feature: About gig module
asoltd/guilds pull request #91
Opened 2022-11-04 17:26 UTC by JakubFrackowiak

Add about gig module. 

Fullscreen: 
![image](https://user-images.githubusercontent.com/91438451/200037973-7b0f19f1-239e-4f79-8e6c-962e91173edf.png)

Mobile:
![image](https://user-images.githubusercontent.com/91438451/200038246-bf8167bf-0286-432e-adf1-adfd368bc7d3.png)

2022-11-05 15:32 UTC, piotrostr requested changes
please check in with Oliwier, he will provide you with introductory review and once you pass Oli's review I'll have another look

2022-11-05 15:32 UTC, piotrostr commented on components/AboutGig/index.tsx
> +          p: { xs: "1rem", sm: "1rem", md: "1rem", lg: "0rem", xl: "0rem" },
if there are 0rem, might skip them

2022-11-05 15:32 UTC, piotrostr commented on components/AboutGig/index.tsx
> +          height: "900px",
why fixed 900px height?

2022-11-05 15:32 UTC, piotrostr commented on components/AboutGig/index.tsx
> +          color: "text.secondary",
color should not be in sx, might be just a prop

2022-11-12 18:45 UTC, OliwierOST commented on components/AboutGig/AboutGig.tsx
> +import { Stack } from "@mui/system"
import every MUI component from `@mui/material`

2022-11-14 14:09 UTC, piotrostr requested changes

2022-11-17 00:57 UTC, piotrostr approved these changes

2022-11-17 00:59 UTC, OliwierOST approved these changes

2022-11-17 01:01 UTC, merged