Feature: Login modules [WIP]
asoltd/guilds pull request #93
Opened 2022-11-05 17:14 UTC by JakubFrackowiak

Sign up:

- Sign up fullscreen:
![image](https://user-images.githubusercontent.com/91438451/200132625-98ed59b0-968a-4195-881d-5a4db71e116a.png)

- Sign up mobile:
![image](https://user-images.githubusercontent.com/91438451/200132649-92ef4e00-2339-4bae-aa5c-ebac652752c6.png)

Sign in:

- Sign in fullscreen:
![image](https://user-images.githubusercontent.com/91438451/200132686-4a32f6c6-1354-4bb5-b3bb-eb0d3f4d857d.png)

- Sign in mobile:
![image](https://user-images.githubusercontent.com/91438451/200132705-40cbc00e-5b74-4c35-9dee-6878d936c7cc.png)

2022-11-05 17:15 UTC, JakubFrackowiak commented
I will fix build today, little busy rn

2023-02-10 10:59 UTC, piotrostr requested changes
@JakubFrackowiak

2023-02-10 10:59 UTC, piotrostr commented on components/SignUp/VerifyPhoneNumber.tsx
> +          +48 123 456 789
this should be the actual number

2023-02-10 10:59 UTC, piotrostr commented on components/SignUp/EmailSignUp.tsx
> +    // TODO this needs try/catch/finally blocks as in SignIn.tsx
this is unresolved

2023-02-10 10:59 UTC, piotrostr commented on components/SignIn/EmailSignIn.tsx
> +  async function resetPassword() {
placeholder method, TODO implement

2023-06-16 18:37 UTC, OliwierOST approved these changes
All good for me, let's hear what @piotrostr has to say.

2023-06-25 13:16 UTC, piotrostr approved these changes

2023-06-25 14:12 UTC, merged